name: Generate Datas
on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:
jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      - name: 🐍 Snake Animation
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: yasminjammeli
          svg_out_path: dist/github-contribution-grid-snake.svg
      - name: crazy-max/ghaction-gh-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
